// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID       string         `gorm:"column:uid;not null" json:"uid"`                                         // UID
	Username  string         `gorm:"column:username;not null" json:"username"`                               // 用户名
	Password  string         `gorm:"column:password;not null" json:"password"`                               // 密码
	Realname  string         `gorm:"column:realname;not null" json:"realname"`                               // 真实姓名
	Mobile    string         `gorm:"column:mobile;not null" json:"mobile"`                                   // 电话号
	AreaCode  int32          `gorm:"column:area_code;not null;default:86" json:"area_code"`                  // 区号
	Email     string         `gorm:"column:email;not null" json:"email"`                                     // EMAIL
	Weixin    string         `gorm:"column:weixin;not null" json:"weixin"`                                   // 微信号
	Unionid   string         `gorm:"column:unionid;not null" json:"unionid"`                                 // 微信平台UnionID
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 修改时间
	Operator  string         `gorm:"column:operator;not null" json:"operator"`                               // 操作人
	IsDeleted bool           `gorm:"column:is_deleted;not null" json:"is_deleted"`                           // 是否删除
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                                    // 删除时间
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
