// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-admin/app/usercenter/internal/biz"
	"kratos-admin/app/usercenter/internal/conf"
	"kratos-admin/app/usercenter/internal/data"
	"kratos-admin/app/usercenter/internal/server"
	"kratos-admin/app/usercenter/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, jwtAuth *conf.JwtAuth, logger log.Logger) (*kratos.App, func(), error) {
	defaultDB := data.NewDefaultDb(confData)
	client := data.NewRds(confData)
	dataData, cleanup, err := data.NewData(confData, defaultDB, client, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, jwtAuth, logger)
	userCenterService := service.NewUserCenterService(userUseCase)
	grpcServer := server.NewGRPCServer(confServer, jwtAuth, userCenterService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
