// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-admin/app/usercenter/internal/biz"
	"kratos-admin/app/usercenter/internal/conf"
	"kratos-admin/app/usercenter/internal/data"
	"kratos-admin/app/usercenter/internal/server"
	"kratos-admin/app/usercenter/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	defaultDB, err := data.NewDefaultDb(confData)
	if err != nil {
		return nil, nil, err
	}
	query := data.NewUserQuery(defaultDB)
	defaultRDS := data.NewDefaultRds(confData)
	dataData, cleanup, err := data.NewData(confData, defaultDB, query, defaultRDS, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	passportRepo := data.NewPassportRepo(dataData, logger)
	passportUseCase := biz.NewPassportUseCase(passportRepo, logger)
	userCenterService := service.NewUserCenterService(userUseCase, passportUseCase)
	grpcServer := server.NewGRPCServer(confServer, userCenterService, logger)
	httpServer := server.NewHTTPServer(confServer, userCenterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
