// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-admin/app/authorization/internal/biz"
	"kratos-admin/app/authorization/internal/conf"
	"kratos-admin/app/authorization/internal/data"
	"kratos-admin/app/authorization/internal/server"
	"kratos-admin/app/authorization/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	defaultDB, err := data.NewDefaultDb(confData)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewRds(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, defaultDB, client, logger)
	if err != nil {
		return nil, nil, err
	}
	roleRepo := data.NewRoleRepo(dataData, logger)
	roleUseCase := biz.NewRoleUseCase(roleRepo, logger)
	authorizationService := service.NewAuthorizationService(roleUseCase)
	grpcServer := server.NewGRPCServer(confServer, authorizationService, logger)
	registrar, err := data.NewRegistrar(registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
